# config.yml

recipe: default.v1
assistant_id: saglik_asistani

language: tr

# NLU Pipeline - TÜRKÇE İÇİN OPTİMİZE EDİLDİ
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  # DIETClassifier - Ana intent ve entity sınıflandırıcı
  - name: DIETClassifier
    epochs: 200  # Artırıldı (100 → 200)
    entity_recognition: True
    use_masked_language_model: False  # Türkçe için False daha iyi
    constrain_similarities: True
    model_confidence: softmax  # linear_norm → softmax (Rasa 3.6.21 uyumlu)
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  # FallbackClassifier - Düşük güven durumunda
  - name: FallbackClassifier
    threshold: 0.7  # Artırıldı (0.3 → 0.7)
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: True