# config.yml

recipe: default.v1
assistant_id: saglik_asistani

# Dil anahtarını, hata vermemesi için tek ve varsayılan bir dile ayarlıyoruz.
language: tr

# NLU Pipeline: Gelen mesajları işleme hattı
pipeline:
  # Bu pipeline, nlu.yml dosyasında lang: etiketiyle bulduğu TÜM diller için çalışacaktır.
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    # DIETClassifier, dil bilgisini bir "entity" olarak yakalayabilir.
    # Bu, LanguageDetector'a olan ihtiyacı ortadan kaldırır.
    entity_recognition: True
    # Bu özellik, modelin hangi dilde konuştuğunu bir entity olarak yakalamasını sağlar.
    use_masked_language_model: True
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Policies bölümü aynı kalabilir.
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100